POST https://eth-bot-backend.herokuapp.com/userexists
Content-Type: application/json

{
    "address": "0x066Adead2d82A1C2700b4B48ee82ec952b6b18dA"
}
###
POST https://localhost::3001/userexists
Content-Type: application/json

{
"address": "0x066Adead2d82A1C2700b4B48ee82ec952b6b18dA"
}